# Generated by Django 2.2 on 2021-07-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOfBanking',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='powerofbanking_powerofbanking', serialize=False, to='cms.CMSPlugin')),
                ('poster', models.ImageField(help_text="plugin poster, it's required", upload_to='power_of_banking/posters')),
                ('title', models.CharField(help_text="plugin title, it's required", max_length=120)),
                ('subtitle', models.CharField(help_text="plugin subtitle, it's required", max_length=120)),
                ('google_play_link', models.URLField(blank=True, help_text="google play application link, it's not required but we prefer to to include it", max_length=160, null=True)),
                ('app_store_link', models.URLField(blank=True, help_text="app store application link, it's not required but we prefer to to include it", max_length=160, null=True)),
                ('logo', models.ImageField(blank=True, help_text="plugin logo, it's not required", null=True, upload_to='power_of_banking/logos')),
                ('logo_subtitle', models.CharField(blank=True, help_text="logo subtitle, under logo subtitle it's not required", max_length=120, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='if is active is true the component will appear else will disappear')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
