# Generated by Django 2.2 on 2021-07-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('powerOfBanking', '0003_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='powerofbanking_cardbox', serialize=False, to='cms.CMSPlugin')),
                ('icon', models.ImageField(upload_to='power_of_banking/icons')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
